export const BASE="/"
export const HOME = "/home"
export const LOGIN = "/login"
export const CATEGORIES = "/categories"
export const TRANSACTIONS = "/transactions"
export const RECURRENT_PAYMENTS = "/recurrentpayments"
export const SETTINGS = "/settings"